Fix typeName for stdlib classes
This is needed as the typeName is used in exception messages.
The previous AttributeError message was e.g. "'org.python.types.x' has no attribute 'y'" which is clearly wrong (uses the Java package path).